create TABLE EMPIDX
As SELECT *
    FROM EMP;
    
select * from empidx;

CREATE INDEX IDX_EMPIDX_EMPNO
    ON EMPIDX (EMPNO);
    
    
SELECT
    *
FROM USER_INDEXES
WHERE INDEX_NAME = 'IDX_EMPIDX_EMPNO';

CREATE OR REPLACE VIEW EMPIDX_OVER15K 
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO, SAL, NVL2(COMM, 'o', 'x') AS COMM
    FROM EMPIDX
    WHERE SAL > 1500);