CREATE TABLE DEPT_FK(
    DEMPNO NUMBER(2) CONSTRAINT DEPTFK_DEPRNO_PK PRIMARY KEY,
    DNAME  VARCHAR2(14),
    LOC VARCHAR(13)
    );
    
CREATE TABLE EMP_FK
    EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPRNO_PK PRIMARY KEY (DEPYNO)
    );
    
insert