CREATE TABLE TABLE_NOYNULL(
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR(20) NOT NULL,
    TEL VARCHAR(20)
    );
    
INSERT INTO TABLE_NOYNULL(LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('TEST_ID_01', NULL, '010-134-5678');

INSERT INTO TABLE_NOYNULL(LOGIN_ID, LOGIN_PWD)
VALUES ('TEST_ID_01', '1234');

SELECT
    *
FROM table_noynull;

UPDATE table_noynull
    SET login_pwd = NULL
    WHERE login_id ='TEST_ID_01';
    
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS;
    
SELECT
    *
FROM TABLE_NOYNULL;

CREATE TABLE TABLE_NOYNULL2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLNN2_LENID_NN NOT NULL,
    LOGIN_PWD  VARCHAR2(20) CONSTRAINT TBLNN2_LENPW_NN NOT NULL,
    TEL VARCHAR(20)
    );