CREATE TABLE TABLE_UNIQUE(
    LOGIN_ID VARCHAR2(20) UNIQUE,
    LOGIN_PWD VARCHAR(20) NOT NULL,
    TEL VARCHAR(20)
);

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'TABLE_UNIQUE'
    
select * from TABLE_UNIQUE;
    
INSERT INTO TABLE_UNIQUE (LOGIN_ID, LOGIN_PWD, LOC)
VALUES (null, 'PWD01', '010-1234-5678');
